
version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true

image: Visual Studio 2015
init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ci-test
cache:
  - c:\projects\ci-test\libs
  - c:\projects\ci-test\test\libs

install:
  - ps: mkdir build
  - ps: cd build
  - ps: $env:CMAKE_GENERATOR_NAME="Visual Studio 14 2015"
  - ps: If("${env:PLATFORM}" -eq "x64") { $env:CMAKE_GENERATOR_NAME="${env:CMAKE_GENERATOR_NAME} Win64" }
  - ps: cmake .. -G "${env:CMAKE_GENERATOR_NAME}" -DVERSION=${env:APPVEYOR_REPO_TAG_NAME}

platform:
  - Win32
  - x64

configuration: Release


for:
-
  branches:
    only:
      - release
  skip_tags: false

  build_script:
    - ps: cd build
    - ps: cmake --build . --target ci_test --config ${env:CONFIGURATION}

  after_build:
    - ps: Move-Item -Path "${env:APPVEYOR_BUILD_FOLDER}\build\${env:CONFIGURATION}\ci_test.lib" -Destination "${env:APPVEYOR_BUILD_FOLDER}\build\${env:CONFIGURATION}\ci_test_${env:PLATFORM}.lib"

  artifacts:
    - path: build\$(configuration)\ci_test_$(platform).lib

  deploy:
    provider: GitHub
    auth_token:
      secure: QNHojv/OaB1ofpE6H1YgTcmqqfyiJBt3+XX7ABZSN9dk1RluUXptNJy2GMGLuxLo
    draft: false
    prereelase: false
    on:
      branch: release
      appveyor_repo_tag: true
